[package]
name = 'candymachinev2'
version = '1.0.0'
[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
candymachinev2 = "6547d9f1d481fdc21cd38c730c07974f2f61adb7063e76f9d9522ab91f090dac" 
aptos_token_objects = "0x4"
[dependencies]
AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git',rev='main',subdir = 'aptos-move/framework/aptos-framework'}
AptosTokenObjects = {git = 'https://github.com/aptos-labs/aptos-core.git',rev='main',subdir = 'aptos-move/framework/aptos-token-objects'}
AptosStdlib = {git = 'https://github.com/aptos-labs/aptos-core.git',rev='main',subdir = 'aptos-move/framework/aptos-stdlib'}
DataStructure = {git = 'https://github.com/aptos-labs/aptos-core.git',rev='main',subdir = 'aptos-move/move-examples/data_structures'}
